import React, { useState, useEffect } from 'react';
import { Link, useNavigate } from 'react-router-dom';

const Register = () => {
  const navigate = useNavigate();
  const [loading, setLoading] = useState(false);
  const [countries, setCountries] = useState([]);
  const [selectedCountry, setSelectedCountry] = useState('');
  const [phone, setPhone] = useState('');

  useEffect(() => {
    fetch('https://restcountries.com/v3.1/all?fields=name,idd')
      .then(res => res.json())
      .then(data => {
        const parsed = data.map(c => {
          let dialCode = '';
          if (c.idd && c.idd.root) {
            dialCode = c.idd.root + (c.idd.suffixes && c.idd.suffixes.length > 0 ? c.idd.suffixes[0] : '');
          }
          return { name: c.name.common, dialCode };
        });
        parsed.sort((a, b) => a.name.localeCompare(b.name));
        setCountries(parsed);
      })
      .catch(err => console.error("Error fetching countries:", err));
  }, []);

  const handleCountryChange = (e) => {
    const countryName = e.target.value;
    setSelectedCountry(countryName);
    
    const countryData = countries.find(c => c.name === countryName);
    if (countryData && countryData.dialCode) {
      setPhone(countryData.dialCode + ' ');
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);

    const formData = new FormData(e.target);
    const data = Object.fromEntries(formData.entries());

    try {
      const response = await fetch('http://localhost:5000/api/register', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(data),
      });

      const result = await response.json();

      if (response.ok) {
        // Redirect to Login page with autogenerated credentials
        navigate('/', { state: { credentials: result.credentials } });
      } else {
        alert(result.error || 'Registration failed');
      }
    } catch (error) {
      console.error('Error submitting form:', error);
      alert('Network error. Please try again later.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="login-container register-container-wrapper">
      <div className="logo-container logo-outside">
        <img src="/logo.png" alt="Traveloop Logo" className="logo" />
      </div>

      <div className="login-card register-card">
        <h1>Create Account</h1>
        <p className="subtitle">Join Traveloop today.</p>
        
        <form id="register-form" onSubmit={handleSubmit} className="login-form register-form-grid">
          <div className="form-row">
            <div className="input-group">
              <label htmlFor="firstName">First Name</label>
              <input type="text" id="firstName" name="firstName" placeholder="First Name" required />
            </div>
            <div className="input-group">
              <label htmlFor="lastName">Last Name</label>
              <input type="text" id="lastName" name="lastName" placeholder="Last Name" required />
            </div>
          </div>
          
          <div className="form-row">
            <div className="input-group">
              <label htmlFor="email">Email Address</label>
              <input type="email" id="email" name="email" placeholder="Email Address" required />
            </div>
            <div className="input-group">
              <label htmlFor="phone">Phone Number</label>
              <input 
                type="tel" 
                id="phone" 
                name="phone" 
                placeholder="Phone Number" 
                value={phone}
                onChange={(e) => setPhone(e.target.value)}
                required 
              />
            </div>
          </div>

          <div className="form-row">
            <div className="input-group">
              <label htmlFor="city">City</label>
              <input type="text" id="city" name="city" placeholder="City" required />
            </div>
            <div className="input-group">
              <label htmlFor="country">Country</label>
              <select 
                id="country" 
                name="country" 
                value={selectedCountry}
                onChange={handleCountryChange}
                required
                className="country-select"
              >
                <option value="" disabled>Select a country</option>
                {countries.map((c, i) => (
                  <option key={i} value={c.name}>{c.name}</option>
                ))}
              </select>
            </div>
          </div>

          <div className="input-group">
            <label htmlFor="additionalInfo">Additional Info</label>
            <textarea id="additionalInfo" name="additionalInfo" placeholder="Tell us more about your travel preferences..." rows="3"></textarea>
          </div>
        </form>
      </div>

      <div className="button-outside-container">
        <button type="submit" form="register-form" className="login-btn register-btn" disabled={loading}>
          {loading ? 'Registering...' : 'Register users'}
        </button>
        <div className="signup-link center-text">
          Already have an account? <Link to="/">Log in</Link>
        </div>
      </div>
    </div>
  );
};

export default Register;
